### PR TITLE
Move logging config into client code

### PR DESCRIPTION
**Pull request by moritzhaller**
Resolves https://github.com/as-ideas/DeepPhonemizer/issues/25

### CODE REVIEW

**Comment by cschaefer26** [comment]
Looks good, but has merge conflicts.

**Comment by moritzhaller** [comment]
@cschaefer26 I rebased and resolved conflicts

**Review by cschaefer26 — APPROVED** [review]

**Comment by moritzhaller** [comment]
@cschaefer26 I don't have write access so feel free to merge :)

**Comment by cschaefer26** [comment]
Merged. I also bumped the pypi version so the fix is available for the package.

**Pull request merged**
